name: GitHub Actions Demo
on: [ push ]
jobs:
  Google-Search:
    runs-on: ubuntu-latest
    steps:
      - name: Run on Linux server
        run: echo "Running on a ${{ runner.os }}"
      - name: Set Java SDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build gradle project
        uses: gradle/gradle-build-action@v2
        with:
          gradle-executable: /gradle/wrapper
          arguments: build
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: cucumber
      - name: Status of job
        run: echo " Status is ${{ job.status }}."
